org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.158.0+26.2

voicechat_version=2.6.22+26.2
voicechat_api_version=2.6.0
audioplayer_roleplay_version=0.4.0+26.2

version=0.1.0
group=de.distantnova.audioperspective
